skeleton/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  root to: redirect('/cats')
  
  resources :users, only: [:new, :create, :destroy]
  
  resource :session, only: [:new, :create, :destroy]
  
  
end

skeleton/app/views/layouts/_login_fields.html.erb
<% unless request.path_info.to_s.chomp == '/users/new'%>
  <form action="<%=session_url%>" method="post">
    
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
      
    <label for="user_name" >
      Username:
      <input type="text" name="user[user_name]" value="">
    </label>
    <br>
    <label for="password" >
      Password:
      <input type="text" name="user[password]" value="">
    </label>
    
      <input type="submit" value="Login">
  </form>

  <form action="<%= new_user_url %>" method="get">
    <input type="submit" value="Sign Up">
  </form>
<% end %>

skeleton/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user == nil%>
      <%= render '/layouts/login_fields' %>
    <% else %>
      Welcome, <%= current_user.user_name %>
      <form action="<%=session_url%>" method="post">
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
        <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Sign out."> 
    </form>
    <% end %>

    <%= yield %>
  </body>
</html>